[package]
name = "kvs"
authors = ["wtf <wtf@wtf.com>"]
description = "A key-value store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^3.0"

[dev-dependencies]
assert_cmd = "^2.0"
predicates = "^2.0"