[package]
name = "kvs"
authors = ["wtf <wtf@wtf.com>"]
description = "A key-value store"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^3.0"
failure = "^0.1"
serde = { version = "^1.0.100", features = ["derive"] }
serde_json = "^1.0.79"

[dev-dependencies]
assert_cmd = "^2.0"
predicates = "^2.0"
tempfile = "3"
walkdir = "2"